const products = [
    // Smartphones
    {
      _id: "65a8e25602e12c44f5995501",
      category: "smartphones",
      name: "iPhone 14",
      brand: "Apple",
      price: 999,
      stock: 50,
      description: "Latest model with advanced features",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
    {
      _id: "65a8e25602e12c44f5995502",
      category: "smartphones",
      name: "Galaxy S23",
      brand: "Samsung",
      price: 899,
      stock: 30,
      description: "High performance with great display",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
  
    // Laptops
    {
      _id: "65a8e25602e12c44f5995503",
      category: "laptops",
      name: "MacBook Pro",
      brand: "Apple",
      price: 1999,
      stock: 20,
      description: "High-end laptop with M1 chip",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
    {
      _id: "65a8e25602e12c44f5995504",
      category: "laptops",
      name: "XPS 13",
      brand: "Dell",
      price: 1199,
      stock: 25,
      description: "Compact and powerful ultrabook",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
  
    // Fragrances
    {
      _id: "65a8e25602e12c44f5995505",
      category: "fragrances",
      name: "Dior Sauvage",
      brand: "Dior",
      price: 120,
      stock: 100,
      description: "A fragrance with a fresh scent",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
    {
      _id: "65a8e25602e12c44f5995506",
      category: "fragrances",
      name: "Chanel No. 5",
      brand: "Chanel",
      price: 150,
      stock: 75,
      description: "Classic scent for timeless elegance",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
  
    // Skincare
    {
      _id: "65a8e25602e12c44f5995507",
      category: "skincare",
      name: "Hydrating Face Cream",
      brand: "Clinique",
      price: 40,
      stock: 60,
      description: "Moisturizes and hydrates skin",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
    {
      _id: "65a8e25602e12c44f5995508",
      category: "skincare",
      name: "Vitamin C Serum",
      brand: "The Ordinary",
      price: 25,
      stock: 80,
      description: "Brightens and evens skin tone",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
  
    // Groceries
    {
      _id: "65a8e25602e12c44f5995509",
      category: "groceries",
      name: "Organic Almonds",
      brand: "Whole Foods",
      price: 15,
      stock: 200,
      description: "High-quality organic almonds",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
    {
      _id: "65a8e25602e12c44f599550a",
      category: "groceries",
      name: "Olive Oil",
      brand: "Bertolli",
      price: 12,
      stock: 150,
      description: "Extra virgin olive oil for cooking",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
  
    // Home Decoration
    {
      _id: "65a8e25602e12c44f599550b",
      category: "home-decoration",
      name: "Decorative Vase",
      brand: "IKEA",
      price: 25,
      stock: 70,
      description: "Stylish vase for home decor",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
    {
      _id: "65a8e25602e12c44f599550c",
      category: "home-decoration",
      name: "Wall Art",
      brand: "Wayfair",
      price: 45,
      stock: 40,
      description: "Modern art piece for wall decor",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
  
    // Furniture
    {
      _id: "65a8e25602e12c44f599550d",
      category: "furniture",
      name: "Wooden Coffee Table",
      brand: "Ashley Furniture",
      price: 120,
      stock: 30,
      description: "Classic wooden coffee table",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
    {
      _id: "65a8e25602e12c44f599550e",
      category: "furniture",
      name: "Office Chair",
      brand: "Herman Miller",
      price: 299,
      stock: 20,
      description: "Ergonomic office chair for comfort",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
  
    // Tops
    {
      _id: "65a8e25602e12c44f599550f",
      category: "tops",
      name: "Cotton T-Shirt",
      brand: "H&M",
      price: 10,
      stock: 100,
      description: "Soft and comfortable t-shirt",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
    {
      _id: "65a8e25602e12c44f5995510",
      category: "tops",
      name: "Silk Blouse",
      brand: "Zara",
      price: 30,
      stock: 50,
      description: "Elegant silk blouse",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
  
    // Women's Dresses
    {
      _id: "65a8e25602e12c44f5995511",
      category: "womens-dresses",
      name: "Floral Maxi Dress",
      brand: "Forever 21",
      price: 50,
      stock: 60,
      description: "Perfect for summer wear",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
    {
      _id: "65a8e25602e12c44f5995512",
      category: "womens-dresses",
      name: "Cocktail Dress",
      brand: "H&M",
      price: 80,
      stock: 40,
      description: "Great for evening events",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
  
    // Men's Shoes
    {
      _id: "65a8e25602e12c44f5995513",
      category: "mens-shoes",
      name: "Running Sneakers",
      brand: "Nike",
      price: 100,
      stock: 50,
      description: "Lightweight sneakers for running",
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },
    {
      _id: "65a8e25602e12c44f5995514",
      category: "mens-shoes",
      name: "Dress Shoes",
      brand: "Clarks",
      price: 120,
      stock: 35,
      description: "Formal shoes for men", 
      mainImage: "https://example.com/images/iphone14/main.jpg",
      images: [
        "https://example.com/images/iphone14/angle1.jpg",
        "https://example.com/images/iphone14/angle2.jpg",
        "https://example.com/images/iphone14/angle3.jpg",
      ],
    },

    // women's watches
    {
        _id: "65a8e25602e12c44f5995515",
        category: "womens-watches",
        name: "Running Sneakers",
        brand: "Nike",
        price: 100,
        stock: 50,
        description: "Lightweight sneakers for running",
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },
      {
        _id: "65a8e25602e12c44f5995516",
        category: "womens-watches",
        name: "Dress Shoes",
        brand: "Clarks",
        price: 120,
        stock: 35,
        description: "Formal shoes for men", 
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },

      // womens-jewellery
    {
        _id: "65a8e25602e12c44f5995517",
        category: "womens-jewellery",
        name: "Running Sneakers",
        brand: "Nike",
        price: 100,
        stock: 50,
        description: "Lightweight sneakers for running",
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },
      {
        _id: "65a8e25602e12c44f5995518",
        category: "womens-jewellery",
        name: "Dress Shoes",
        brand: "Clarks",
        price: 120,
        stock: 35,
        description: "Formal shoes for men", 
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },

      // mens-shirts
    {
        _id: "65a8e25602e12c44f5995519",
        category: "mens-shirts",
        name: "Running Sneakers",
        brand: "Nike",
        price: 100,
        stock: 50,
        description: "Lightweight sneakers for running",
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },
      {
        _id: "65a8e25602e12c44f5995520",
        category: "mens-shirts",
        name: "Dress Shoes",
        brand: "Clarks",
        price: 120,
        stock: 35,
        description: "Formal shoes for men", 
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },

      // sunglasses
    {
        _id: "65a8e25602e12c44f5995521",
        category: "sunglasses",
        name: "Running Sneakers",
        brand: "Nike",
        price: 100,
        stock: 50,
        description: "Lightweight sneakers for running",
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },
      {
        _id: "65a8e25602e12c44f5995522",
        category: "sunglasses",
        name: "Dress Shoes",
        brand: "Clarks",
        price: 120,
        stock: 35,
        description: "Formal shoes for men", 
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },

      // womens-shoes
    {
        _id: "65a8e25602e12c44f5995523",
        category: "womens-shoes",
        name: "Running Sneakers",
        brand: "Nike",
        price: 100,
        stock: 50,
        description: "Lightweight sneakers for running",
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },
      {
        _id: "65a8e25602e12c44f5995524",
        category: "womens-shoes",
        name: "Dress Shoes",
        brand: "Clarks",
        price: 120,
        stock: 35,
        description: "Formal shoes for men", 
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },

      // lighting
    {
        _id: "65a8e25602e12c44f5995525",
        category: "lighting",
        name: "Running Sneakers",
        brand: "Nike",
        price: 100,
        stock: 50,
        description: "Lightweight sneakers for running",
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },
      {
        _id: "65a8e25602e12c44f5995526",
        category: "lighting",
        name: "Dress Shoes",
        brand: "Clarks",
        price: 120,
        stock: 35,
        description: "Formal shoes for men", 
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },

      // automotive 
    {
        _id: "65a8e25602e12c44f5995527",
        category: "automotive",
        name: "Running Sneakers",
        brand: "Nike",
        price: 100,
        stock: 50,
        description: "Lightweight sneakers for running",
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },
      {
        _id: "65a8e25602e12c44f5995528",
        category: "automotive",
        name: "Dress Shoes",
        brand: "Clarks",
        price: 120,
        stock: 35,
        description: "Formal shoes for men", 
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },

      // womens-bags
    {
        _id: "65a8e25602e12c44f5995529",
        category: "womens-bags",
        name: "Running Sneakers",
        brand: "Nike",
        price: 100,
        stock: 50,
        description: "Lightweight sneakers for running",
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },
      {
        _id: "65a8e25602e12c44f5995530",
        category: "womens-bags",
        name: "Dress Shoes",
        brand: "Clarks",
        price: 120,
        stock: 35,
        description: "Formal shoes for men", 
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },

      // mens-watches
    {
        _id: "65a8e25602e12c44f5995531",
        category: "mens-watches",
        name: "Running Sneakers",
        brand: "Nike",
        price: 100,
        stock: 50,
        description: "Lightweight sneakers for running",
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },
      {
        _id: "65a8e25602e12c44f5995532",
        category: "mens-watches",
        name: "Dress Shoes",
        brand: "Clarks",
        price: 120,
        stock: 35,
        description: "Formal shoes for men", 
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },

      // motorcycle
    {
        _id: "65a8e25602e12c44f5995533",
        category: "motorcycle",
        name: "Running Sneakers",
        brand: "Nike",
        price: 100,
        stock: 50,
        description: "Lightweight sneakers for running",
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },
      {
        _id: "65a8e25602e12c44f5995534",
        category: "motorcycle",
        name: "Dress Shoes",
        brand: "Clarks",
        price: 120,
        stock: 35,
        description: "Formal shoes for men", 
        mainImage: "https://example.com/images/iphone14/main.jpg",
        images: [
          "https://example.com/images/iphone14/angle1.jpg",
          "https://example.com/images/iphone14/angle2.jpg",
          "https://example.com/images/iphone14/angle3.jpg",
        ],
      },
  
  ];
  